name: Sort Table

on:
  push:
    branches:
      - main  # Adjust if your main branch is different

jobs:
  sort-table:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install markdown-table

      - name: Sort Table
        run: |
          npx markdown-table -i README.md -s '#' --sort-ascending
          
      - name: Commit Changes
        run: |
          git config --local user.email "mannan.jnv123@gmail.com"
          git config --local user.name "abdul1mannan"
          git commit -am "Automatically sorted table"
          git push
