name: Sort LeetCode Problems

on:
  push:
    branches:
      - main  # Adjust if your main branch has a different name

jobs:
  sort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Sort LeetCode Problems
        run: |
          sed -i '/^| # | Title | Solution | Difficulty |$/d' README.md
          sort -n -t "|" -k2 README.md > temp.md
          mv temp.md README.md
          
      - name: Commit Changes
        run: |
          git config --local user.email "mannan.jnv123@gmail.com"  # Replace with your email
          git config --local user.name "abdul1mannan"  # Replace with your GitHub username
          git add README.md
          git commit -m "Auto sort LeetCode problems"
          git push
